server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /miniblog
spring:
  data:
    mongodb:
      host: 114.115.222.43
      port: 27017
      database: chatroom
    rest:
      basePath: /miniblog/data
      defaultPageSize: 10
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true


